# Generated by Django 3.0.5 on 2020-05-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_auto_20200503_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitant',
            name='mdp',
            field=models.CharField(default='***********', max_length=50),
        ),
    ]
