# Generated by Django 3.0.3 on 2020-05-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_habitant_mdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_produits', models.CharField(choices=[('1', '1 '), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', help_text='Veuillez indiquer le nombre de produits que vous désirez', max_length=50)),
                ('produit', models.CharField(choices=[('pâtes', 'pâtes'), ('riz', 'riz'), ('semoule', 'semoule'), ('céréales', 'céréales'), ('farine', 'farine'), ('sucre', 'sucre'), ('oeufs', 'oeufs'), ('blancs de poulet', 'blancs de poulet'), ('steaks hâchés', 'steaks hâchés (boeuf)'), ('jambon', 'jambon (porc)'), ('jambon de dinde', 'jambon de dinde'), ('yaourt', 'yaourt'), ('fromage', 'fromage'), ('parmesan', 'parmesan râpé'), ('pomme', 'pomme'), ('banane', 'banane'), ('orange', 'orange'), ('courgette', 'courgette'), ('carotte', 'carotte'), ('pommes de terre', 'pommes de terre')], help_text='Veuillez sélectionner un produit dans la liste demandée', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='habitant',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='habitant',
            name='foyer',
            field=models.ForeignKey(help_text='Veuillez sélectionner le dernier foyer svp.', on_delete=django.db.models.deletion.CASCADE, to='appone.Foyer'),
        ),
    ]
