# Generated by Django 3.0.3 on 2020-05-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_auto_20200506_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectivite',
            fields=[
                ('id', models.CharField(default='Entrez votre identifiant', max_length=15, primary_key=True, serialize=False)),
                ('ville', models.CharField(default='Entrez votre ville', max_length=70)),
                ('mdp', models.CharField(default='***********', max_length=50)),
            ],
        ),
    ]
